### ISSUE TITLE
Move into Ember

### ISSUE THREAD

**Issue by sandstrom** [ef4/ember-ignore-children-helper#2]
This is an awesome addon! 🏅 

Has there been any discussion on moving this into Ember, as an option (similar to `on=` or `preventDefault=`)?

**Comment by ef4** [comment]
I'm not aware of any discussion. I don't know if it's a common enough need to justify adding to the public API of Ember. But if you want to champion that, you could open an issue on the ember RFCs repo (issues are for discussing a change, PRs are for when you have already crafted a detailed proposal).

**Comment by sandstrom** [comment]
Thanks for a quick reply @ef4!
